# Broadcasting
allows you to perform artimatic operations with tensors with different shapes

In [6]:
import torch
a = torch.tensor([2,3,4])
b = torch.tensor([5,6,7])

print(a)
print()
print(b)
# print()
# print(a.shape)
# print(b.shape)

tensor([2, 3, 4])

tensor([5, 6, 7])

torch.Size([3])
torch.Size([3])


In [8]:
print(a+b)
print()
print(a-b)

tensor([ 7,  9, 11])

tensor([-3, -3, -3])


Change shape of mis matching tensors to perform artimatic operations on intuitive element to element


In [11]:
tensor1 = torch.tensor([[1,2,3]])
tensor2 = torch.tensor([[4],[5],[6]])

print(tensor1.shape)
print()
print(tensor2.shape)


torch.Size([1, 3])

torch.Size([3, 1])


not all tensors are broadcastable. There is a test, to see if we can change the shape


Test :


1. __Are they equal to each other i.r Tensor1 = Tensor2__
or
2. __If one of the dimensions is 1__

What is the shape of resulting tensor?


In [ ]:
# works
(1,3)
(3,1)

In [ ]:
# we copy the values so that the shape is the same as the resulting tensor

[[1,2,3]] ---> [(1,2,3),[1,2,3],[1,2,3]]
#from (1,3) to (3,3)

[[4],                   [[4,4,4]]
 [5],      -------->    [[5,5,5]]
 [6]]                   [[6,6,6]]

#from (3,1) to (3,3)

In [ ]:
# expected

[[5,6,7]
 [6,7,8]
 [7,8,9]]

In [12]:
tensor1+tensor2

tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])

In [ ]:
# doesnt work
(1,3)
(3,4)

In [15]:
a = torch.tensor([[1,2,3]])
b = torch.tensor([9])
a*b

tensor([[ 9, 18, 27]])

In [16]:
print(a.shape)
print()
print(b.shape)


torch.Size([1, 3])

torch.Size([1])


In [24]:
a = torch.tensor([[1,2,3]])
b = torch.tensor([9,5])
a*b

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [25]:
print(a.shape)
print()
print(b.shape)

torch.Size([1, 3])

torch.Size([2])


In [30]:
# add 1 for lower dimensinal tensor if empty

a = torch.tensor([[1,2,3]])
b = torch.tensor([9,5,1])
a*b

tensor([[ 9, 10,  3]])

In [31]:
print(a.shape)
print()
print(b.shape)

torch.Size([1, 3])

torch.Size([3])
